### ISSUE TITLE
Getting an error !!

### ISSUE THREAD

**Issue by Evil2S** [samadii/YTChannelContentsList#1]
https://github.com/samadii/YTChannelContentsList/blob/37072fb687d657a3f6125411f24450c2e4f1d97e/main.py#L40

**Comment by Evil2S** [comment]
![image](https://user-images.githubusercontent.com/90159347/142483984-e0f6477b-58bc-464f-a61e-4dcc62f40c17.png)

**Comment by samadii** [comment]
Check again, It seems be fixed.
I also added a installation tutorial in the [readme](https://github.com/samadii/YTChannelContentsList/blob/master/README.md).

**Comment by Evil2S** [comment]
> Check again, It seems be fixed. I also added a installation tutorial in the [readme](https://github.com/samadii/YTChannelContentsList/blob/master/README.md).

Okay thanks !  I will check :)
